### ISSUE TITLE
Host / Deploy Website

### ISSUE THREAD

**Issue by baldwmic** [baldwmic/baldwmic.github.io#2]
Domain Name Registrar: gandi.net
Static Website Hosting: netlify.com

- [x] Continuous deployment through one command / one push
  - [x] baldwmic.github.io should show latest build in master
  - [x] pushing to master deploys to michaelbaldwin.netlify.com
  - [x] traffic from michaelbaldwin.net should be redirected to michaelbaldwin.netlify.com server
- [x] Custom Domain name (point michaelbaldwin.net to static hosting url): https://www.netlify.com/docs/custom-domains/
  - [x] Gandi DNS zonefile with CNAME record
  - [x] wait 3 hours for dns changes to propagate
  - [x] disable custom domain in baldwmic.github.io repo, delete CNAME file from github repo
  - [x] confirm github cname isn't still an issue
- [x] HTTPS/SSL: https://www.netlify.com/docs/ssl/
  - [x] Enable in netlify

**Comment by baldwmic** [comment]
Github Pages does not allow SSL for custom domains, so switching to netlify. Other benefit of using netlify, is we could use a build command with their docker container to build the static website, meaning we don't have to push a build to master branch

**Comment by cashc** [comment]
how much is your domain and hosting /year?

**Comment by baldwmic** [comment]
@cashc 

Domain Name Registrar: [Gandi](https://www.gandi.net/) - $15/year * 
Hosting: [Netlify](https://www.netlify.com/pricing/) - Free

* Price for registering a domain name varies significantly. Gandi's motto is a great answer to using companies like Hostgator or GoDaddy, whom I find particularly annoying.
